wandb:
  experiment_name: ''
  project: 'ColourInteract Sweeps Monday no-OOD Debug'
  entity: 'commute_opt_gnn'

data:
  name: ColourInteract
  dataset : 'LRGB'
  num_colours: 4
  train_size: 1500
  val_size: 150
  min_train_nodes: 75
  max_train_nodes: 125
  min_val_nodes: 75
  max_val_nodes: 125
  rewirers: ["cayley_clusters", "cayley"]
  normalise: True
  seed: 91

model:
  hidden_channels: 8
  num_layers: 5
  drop_prob: 0.1
  global_pool_aggr: global_mean_pool
  approaches: ["interleave", "only_original"]
  seeds: [17] # , 71, 117
  norm: ln
  
train:
  lr: 0.001
  warmup: 50
  gamma_decay: 0.95
  num_epochs: 200
  print_every: 10
  train_batch_size: 128
  val_batch_size: 128
  loss_fn: "MSE"

run:
  silent: False