wandb:
  experiment_name: ''
  project: 'ColourInteract Sweeps'
  entity: 'commute_opt_gnn'

data:
  name: ColourInteract
  dataset : 'LRGB'
  c1: 1.0
  c2: 50.0
  num_colours: 4
  train_size: 1000
  val_size: 100
  min_train_nodes: 75
  max_train_nodes: 125
  min_val_nodes: 125
  max_val_nodes: 150
  rewirers: ["cayley_clusters", "cayley"]
  normalise: True
  seed: 91

model:
  hidden_channels: 8
  num_layers: 5
  drop_prob: 0.0
  global_pool_aggr: global_mean_pool
  approach: "interleave"
  seeds: [73, 47, 23]
  

train:
  lr: 0.0001
  num_epochs: 200
  print_every: 1
  train_batch_size: 32
  val_batch_size: 32

run:
  silent: False