wandb:
  experiment_name: ''
  project: 'ColourInteract Sweeps'
  entity: 'commute_opt_gnn'

data:
  name: ColourInteract
  dataset : 'LRGB'
  c2_over_c1: 50
  num_colours: 4
  train_size: 1500
  val_size: 300
  min_train_nodes: 75
  max_train_nodes: 125
  min_val_nodes: 125
  max_val_nodes: 175
  rewirers: ["cayley", "cayley_clusters"]
  normalise: True
  seed: 91

model:
  hidden_channels: 8
  num_layers: 5
  drop_prob: 0.5
  global_pool_aggr: global_add_pool
  approach: "interleave"
  seed: 73
  norm: ln

train:
  lr: 0.0001
  num_epochs: 200
  print_every: 10
  train_batch_size: 32
  val_batch_size: 32
  loss_fn: "MSE"

run:
  silent: False