data:
  dataset : 'LRGB'
  c1: 1.0
  c2: 5.0
  num_colours: 5
  train_size: 2000
  val_size: 300
  min_train_nodes: 100
  max_train_nodes: 150
  max_val_nodes: 200

model:
  hidden_channels: 8
  num_layers: 5
  drop_prob: 0.0

train:
  lr: 0.001
  num_epochs: 200
  print_every: 10
  train_batch_size: 128
  val_batch_size: 128

run:
  silent: False