wandb:
  experiment_name: ''
  project: 'ColourInteract Sweeps'
  entity: 'commute_opt_gnn'

data:
  name: ColourInteract
  dataset : 'LRGB'
  c1: 1.0
  c2: 5.0
  num_colours: 3
  train_size: 2000
  val_size: 300
  min_train_nodes: 100
  max_train_nodes: 150
  max_val_nodes: 200
  seeds: [73, 47, 23]
  rewirers: ["cayley_clusters", "cayley", "fully_connected"]
  normalise: False



model:
  hidden_channels: 8
  num_layers: 5
  drop_prob: 0.0
  global_pool_aggr: global_mean_pool
  approach: "interleave"
  

train:
  lr: 0.001
  num_epochs: 200
  print_every: 10
  train_batch_size: 512
  val_batch_size: 512

run:
  silent: True