data:
  c1: 0.7
  c2: 0.3
  c3: 0.01
  d: 5
  train_size: 500
  val_size: 100
  train_test_size_boundary: 30

model:
  hidden_channels: 8
  num_layers: 5
  drop_prob: 0.0

train:
  lr: 0.001
  num_epochs: 200
  print_every: 10
  train_batch_size: 32
  val_batch_size: 32

run:
  silent: False