wandb:
  project: 'OGBN-ARXIV 12.03'
  entity: 'commute_opt_gnn'

model:
  hidden_channels: 128
  num_layers: 3
  drop_prob: 0.5
  rewirers: ["class_train_only", "class_all", "mlp_all", "knn", "knn_mlp_feats"]
  approaches: ["only_original", "interleave"]
  norm: 'bn'
  seed: 42
  
train:
  lr: 0.001
  num_epochs: 400
  print_every: 10
  verbose: True
  log_wandb: True

run:
  silent: False
